apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: thesis-dev
resources:
  - namespace.yaml
  - ingress.yaml
  - frontend-web.yaml
  - api-gateway.yaml
  - auth-service.yaml
  - user-service.yaml
  - product-service.yaml
  - order-service.yaml
  - notification-service.yaml
