apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thesis-microservices-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mhieudzvcl/NT114.Q21.git
    targetRevision: main
    path: gitops/apps/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: thesis-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
