name: iac-security

on:
  pull_request:
    paths:
      - "infra/terraform/**"
  workflow_dispatch:
  push:
    branches: [ "main", "develop" ]
    paths:
      - "infra/terraform/**"
      - ".github/workflows/iac-security.yml"

jobs:
  terraform-security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform/environments/dev
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
      - name: Terraform fmt
        run: terraform fmt -recursive ../../
      - name: Terraform init
        run: terraform init -backend=false
      - name: Terraform validate
        run: terraform validate
      - name: TFLint
        uses: terraform-linters/setup-tflint@v4
      - run: tflint --init && tflint
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: infra/terraform
          soft_fail: true
      - name: Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra/terraform
          quiet: true
          soft_fail: true
